version: "3.9"

x-mergin-client-image: &mergin-client-image kartoza/mergin-client:latest

volumes:
  qgis_projects:

services:

  download-project:
    image: *mergin-client-image
    env_file: .env
    environment:
      - MERGIN_URL=${MERGIN_URL}
      - MERGIN_USER=${MERGIN_USER}
      - MERGIN_PASSWORD=${MERGIN_PASSWORD}
    command: "download tim1/GloriousProjectOfMagnificence /home/mergin/project"
      #command: "/bin/sh -c 'set -x; mergin.sh download $MERGIN_PROJECT; while :; do sleep 1m & wait $${!}; set -x; cd $MERGIN_PROJECT; mergin pull; cd ..; done' "
    volumes:
      - qgis_projects:/home/mergin

  pull-projects:
    image: *mergin-client-image
    env_file: .env
    environment:
      - MERGIN_URL=${MERGIN_URL}
      - MERGIN_USER=${MERGIN_USER}
      - MERGIN_PASSWORD=${MERGIN_PASSWORD}
    command: "pull"
    volumes:
      - qgis_projects:/home/mergin

  list-shared-projects:
    image: *mergin-client-image
    env_file: .env
    environment:
      - MERGIN_URL=${MERGIN_URL}
      - MERGIN_USER=${MERGIN_USER}
      - MERGIN_PASSWORD=${MERGIN_PASSWORD}
    command: "list-projects --flag shared"
    volumes:
      - qgis_projects:/home/mergin

  download-shared-projects:
    image: *mergin-client-image
    env_file: .env
    environment:
      - MERGIN_URL=${MERGIN_URL}
      - MERGIN_USER=${MERGIN_USER}
      - MERGIN_PASSWORD=${MERGIN_PASSWORD}
    command: "download-shared"
    volumes:
      - qgis_projects:/home/mergin
