version: "3.9"

x-mergin-client-image: &mergin-client-image kartoza/mergin-client:latest

volumes:
  qgis_projects:

services:

  mergin-client:
    image: *mergin-client-image
    env_file: .env
    environment:
      - MERGIN_URL=${MERGIN_URL}
      - MERGIN_USER=${MERGIN_USER}
      - MERGIN_PASSWORD=${MERGIN_PASSWORD}
    command: "download tim1/GloriousProjectOfMagnificence /home/mergin/"
      #command: "/bin/sh -c 'set -x; mergin.sh download $MERGIN_PROJECT; while :; do sleep 1m & wait $${!}; set -x; cd $MERGIN_PROJECT; mergin pull; cd ..; done' "
    volumes:
      - qgis_projects:/home/mergin
